import fs from "node:fs/promises";
import { optimize } from "svgo";
import { renderIgnoreComments } from "./render";
import type { IgnoreComment, OptimizeSvgOptions, SyncResult } from "./types";
import { optimizeSvg } from "./svgo";
import { toCase } from "./utils";

export async function readSpritesheetInput({
  input,
  nameCase,
  convertColors = false,
}: {
  input: string;
  nameCase?: "camel" | "kebab" | "snake" | "lower" | "pascal";
  convertColors?: boolean;
}): Promise<SyncResult["tokens"]> {
  const entries = await fs.readdir(input, {
    withFileTypes: true,
  });

  const svgFiles = entries.filter((entry) => entry.isFile() && entry.name.endsWith(".svg"));

  const optimizeOptions: OptimizeSvgOptions | undefined =
    convertColors === false ? [["convertColors", false]] : undefined;

  const tokens = await Promise.all(
    svgFiles.map(async (file) => {
      const source = await fs.readFile(`${input}/${file.name}`, "utf-8");
      const value = optimizeSvg(source, optimizeOptions);
      const name = toCase(file.name.replace(/\.svg$/i, ""), nameCase || "kebab");

      return { group: "_", name, value };
    }),
  );

  return tokens;
}

export async function generateSpritesheet({
  tokens,
  spriteDir,
  spriteFilename,
  idsEnabled,
  idsFilename,
  idsFileType = "ts",
  idsDir,
  idsIgnoreComments,
}: {
  tokens: SyncResult["tokens"][0][];
  spriteDir: string;
  spriteFilename: string;
  idsEnabled: boolean;
  idsFilename: string;
  idsFileType?: "ts" | "js" | "json";
  idsDir: string;
  idsIgnoreComments?: readonly IgnoreComment[];
}) {
  const symbols: [string, string][] = [];

  tokens.forEach(({ name, value }) => {
    if (typeof value !== "string") return;

    const symbol = createSpriteSymbol({ name, svg: value });

    if (symbol) {
      symbols.push([name, symbol]);
    }
  });

  const spritesheet =
    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs>' +
    symbols.map(([, symbol]) => symbol).join("") +
    "</defs></svg>";

  await fs.writeFile(`${spriteDir}/${spriteFilename}.svg`, spritesheet, "utf-8");

  if (!idsEnabled) return;

  const ids = symbols.map(([name]) => JSON.stringify(name)).join(",");

  const ignoreComments = renderIgnoreComments(idsIgnoreComments);

  let idsFileContent = "";

  if (idsFileType === "ts") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}] as const;\n`;
  } else if (idsFileType === "js") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}];\n`;
  } else if (idsFileType === "json") {
    idsFileContent = JSON.stringify(
      symbols.map(([name]) => name),
      null,
      2,
    );
  }

  await fs.writeFile(`${idsDir}/${idsFilename}.${idsFileType}`, idsFileContent, "utf-8");
}

function createSpriteSymbol({ name, svg }: { name: string; svg: string }): string | undefined {
  let isSvg = false;

  const { data } = optimize(svg, {
    plugins: [
      "removeDoctype",
      "removeXMLProcInst",
      {
        name: "convertSvgToSymbol",
        fn: () => ({
          element: {
            enter: (node, parentNode) => {
              if (parentNode.type !== "root" || node.name !== "svg") return;

              isSvg = true;
              node.name = "symbol";
              node.attributes.id = name;
              delete node.attributes.xmlns;
              delete node.attributes["xmlns:xlink"];
            },
          },
        }),
      },
    ],
  });

  return isSvg ? data : undefined;
}
