import fs from "node:fs/promises";
import type { SyncResult } from "./types";
import { pascalCase } from "./utils";

export async function generateSpritesheet({
  name,
  tokens,
  spriteDir,
  spriteFilename,
  idsEnabled,
  idsFilename,
  idsFileType = "ts",
  idsDir,
}: {
  name: string;
  tokens: SyncResult["tokens"][0][];
  spriteDir: string;
  spriteFilename: string;
  idsEnabled: boolean;
  idsFilename: string;
  idsFileType?: "ts" | "js" | "json";
  idsDir: string;
}) {
  const svgs: [string, string][] = [];

  tokens.forEach(({ name, value }) => {
    if (typeof value !== "string") return;

    const rgx = /<svg.*?>([\s\S]*)<\/svg>/i;
    const match = value.match(rgx);
    const svgContent = match ? match[1] : "";

    if (svgContent) {
      svgs.push([name, svgContent]);
    }
  });

  const symbols = svgs
    .map(
      ([name, svgContent]) =>
        `<symbol viewBox="0 0 24 24" id="${name}">${svgContent}</symbol>`,
    )
    .join("");

  const spritesheet =
    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs>' +
    symbols +
    "</defs></svg>";

  await fs.writeFile(
    `${spriteDir}/${spriteFilename}.svg`,
    spritesheet,
    "utf-8",
  );

  if (!idsEnabled) return;

  const ids = svgs.map(([name]) => JSON.stringify(name)).join(",");
  const typeName = pascalCase(`${name}Name`);

  const ignoreComments =
    "/* eslint-disable */\n" +
    "/* prettier-ignore */\n" +
    "/* oxlint-disable */\n" +
    "/* oxfmt-ignore */\n";

  let idsFileContent = "";

  if (idsFileType === "ts") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}] as const;\n` +
      `export type ${typeName} = (typeof ids)[number];\n`;
  } else if (idsFileType === "js") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}];\n`;
  } else if (idsFileType === "json") {
    idsFileContent = JSON.stringify(
      svgs.map(([name]) => name),
      null,
      2,
    );
  }

  await fs.writeFile(
    `${idsDir}/${idsFilename}.${idsFileType}`,
    idsFileContent,
    "utf-8",
  );
}
