import fs from "node:fs/promises";
import type { OptimizeSvgOptions, SyncResult } from "./types";
import { optimizeSvg } from "./svgo";
import { toCase } from "./utils";

export async function readSpritesheetInput({
  input,
  nameCase,
  convertColors = false,
}: {
  input: string;
  nameCase?: "camel" | "kebab" | "snake" | "lower" | "pascal";
  convertColors?: boolean;
}): Promise<SyncResult["tokens"]> {
  const entries = await fs.readdir(input, {
    withFileTypes: true,
  });

  const svgFiles = entries.filter((entry) => entry.isFile() && entry.name.endsWith(".svg"));

  const optimizeOptions: OptimizeSvgOptions | undefined =
    convertColors === false ? [["convertColors", false]] : undefined;

  const tokens = await Promise.all(
    svgFiles.map(async (file) => {
      const source = await fs.readFile(`${input}/${file.name}`, "utf-8");
      const value = optimizeSvg(source, optimizeOptions);
      const name = toCase(file.name.replace(/\.svg$/i, ""), nameCase || "kebab");

      return { group: "_", name, value };
    }),
  );

  return tokens;
}

export async function generateSpritesheet({
  tokens,
  spriteDir,
  spriteFilename,
  idsEnabled,
  idsFilename,
  idsFileType = "ts",
  idsDir,
}: {
  tokens: SyncResult["tokens"][0][];
  spriteDir: string;
  spriteFilename: string;
  idsEnabled: boolean;
  idsFilename: string;
  idsFileType?: "ts" | "js" | "json";
  idsDir: string;
}) {
  const svgs: [string, string][] = [];

  tokens.forEach(({ name, value }) => {
    if (typeof value !== "string") return;

    const rgx = /<svg.*?>([\s\S]*)<\/svg>/i;
    const match = value.match(rgx);
    const svgContent = match ? match[1] : "";

    if (svgContent) {
      svgs.push([name, svgContent]);
    }
  });

  const symbols = svgs
    .map(([name, svgContent]) => `<symbol viewBox="0 0 24 24" id="${name}">${svgContent}</symbol>`)
    .join("");

  const spritesheet =
    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs>' +
    symbols +
    "</defs></svg>";

  await fs.writeFile(`${spriteDir}/${spriteFilename}.svg`, spritesheet, "utf-8");

  if (!idsEnabled) return;

  const ids = svgs.map(([name]) => JSON.stringify(name)).join(",");

  const ignoreComments =
    "/* eslint-disable */\n" +
    "/* prettier-ignore */\n" +
    "/* oxlint-disable */\n" +
    "/* oxfmt-ignore */\n";

  let idsFileContent = "";

  if (idsFileType === "ts") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}] as const;\n`;
  } else if (idsFileType === "js") {
    idsFileContent =
      "/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */\n" +
      ignoreComments +
      `export const ids = [${ids}];\n`;
  } else if (idsFileType === "json") {
    idsFileContent = JSON.stringify(
      svgs.map(([name]) => name),
      null,
      2,
    );
  }

  await fs.writeFile(`${idsDir}/${idsFilename}.${idsFileType}`, idsFileContent, "utf-8");
}
