/* ------------------ AUTO-GENERATED BY FIGMAGE ------------------ */
/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
export const ids = ["github","home","pen","twitter"] as const;
